# -*- coding: utf-8 -*-
"""salary_dashboard.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1255t_GB8j1YTx9-JONdHuYtPV6BccEO-
"""

!pip install streamlit pyngrok pandas plotly

!ngrok config add-authtoken 3C1rTe1mc7fIOatP9JAjHCKWfe2_6EzCnnnW6N1bE8eCnpyja

from google.colab import files
uploaded = files.upload()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile salary_dashboard_final.py
# import streamlit as st
# import pandas as pd
# import plotly.express as px
# 
# # ---------------- PAGE CONFIG ----------------
# st.set_page_config(page_title="💼 Salary Dashboard", layout="wide")
# 
# # ---------------- TITLE ----------------
# st.title(" Salary Data Dashboard ")
# 
# # ---------------- LOAD DATASET ----------------
# df = pd.read_csv("batch 7 dataset-salary.csv")
# df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
# 
# # ---------------- DATASET PREVIEW ----------------
# st.subheader("📊 Dataset Preview")
# st.dataframe(df)
# 
# # ---------------- FILTER ----------------
# st.sidebar.header("🎯 Filter Options")
# 
# if "Location" in df.columns:
#     loc = st.sidebar.multiselect("📍 Location", df["Location"].unique())
#     if loc:
#         df = df[df["Location"].isin(loc)]
# 
# if "Job Title" in df.columns:
#     job = st.sidebar.multiselect("💼 Job Role", df["Job Title"].unique())
#     if job:
#         df = df[df["Job Title"].isin(job)]
# 
# # ---------------- FILTERED DATA ----------------
# st.subheader("🔍 Filtered Data")
# st.dataframe(df)
# 
# # ---------------- KEY METRICS ----------------
# st.subheader("📈 Key Metrics")
# c1, c2, c3 = st.columns(3)
# c1.metric("📄 Total Records", len(df))
# if "Salary" in df.columns:
#     c2.metric("💰 Avg Salary", int(df["Salary"].mean()))
#     c3.metric("🚀 Max Salary", int(df["Salary"].max()))
# 
# # ---------------- HIGHEST PAID JOB ----------------
# if "Salary" in df.columns:
#     st.subheader("🏆 Highest Paid Job")
#     max_row = df.loc[df["Salary"].idxmax()]
#     st.write("💼 Job:", max_row.get("Job Title", "N/A"))
#     st.write("🏢 Company:", max_row.get("Company Name", "N/A"))
#     st.write("💰 Salary:", max_row["Salary"])
# 
# # ---------------- GRAPH STYLE ----------------
# template_style = "plotly_dark"
# 
# # ---------------- GRAPH 1: Salary Distribution ----------------
# st.subheader("📊 Salary Distribution")
# fig1 = px.histogram(df, x="Salary", template=template_style)
# fig1.update_traces(marker_line_width=0.5)
# fig1.update_layout(height=500)
# st.plotly_chart(fig1, use_container_width=True)
# 
# # ---------------- GRAPH 2: Salary vs Rating ----------------
# if "Rating" in df.columns:
#     st.subheader("⭐ Salary vs Rating")
#     fig2 = px.scatter(df, x="Rating", y="Salary", template=template_style)
#     fig2.update_traces(marker=dict(size=6))
#     fig2.update_layout(height=500)
#     st.plotly_chart(fig2, use_container_width=True)
# 
# # ---------------- GRAPH 3: Experience vs Salary ----------------
# if "Experience" in df.columns:
#     st.subheader("📈 Experience vs Salary")
#     exp = df.groupby("ExperienceSalary"].mean().reset_index()
#     fig3 = px.line(exp, x="Experience", y="Salary", template=template_style)
#     fig3.update_traces(line=dict(width=2))
#     fig3.update_layout(height=500)
#     st.plotly_chart(fig3, use_container_width=True)
# 
# # ---------------- GRAPH 4: Top Companies ----------------
# if "Company Name" in df.columns:
#     st.subheader("🏢 Top Companies")
#     comp = df["Company Name"].value_counts().head(10).reset_index()
#     comp.columns = ["Company", "Count"]
#     fig4 = px.bar(comp, x="Company", y="Count", template=template_style)
#     fig4.update_traces(marker_line_width=0.5)
#     fig4.update_layout(height=500)
#     st.plotly_chart(fig4, use_container_width=True)
# 
# # ---------------- GRAPH 5: Job Role Distribution ----------------
# if "Job Title" in df.columns:
#     st.subheader("🥧 Job Role Distribution")
#     fig5 = px.pie(df, names="Job Title", template=template_style)
#     fig5.update_layout(height=500)")["
#     st.plotly_chart(fig5, use_container_width=True)
# 
# # ---------------- GRAPH 6: Top Job Roles ----------------
# if "Job Title" in df.columns:
#     st.subheader("📊 Top Job Roles")
#     roles = df["Job Title"].value_counts().head(10).reset_index()
#     roles.columns = ["Role", "Count"]
#     fig6 = px.bar(roles, x="Role", y="Count", template=template_style)
#     fig6.update_layout(height=500)
#     st.plotly_chart(fig6, use_container_width=True)
# 
# # ---------------- GRAPH 7: Rating Distribution ----------------
# if "Rating" in df.columns:
#     st.subheader("⭐ Rating Distribution")
#     fig7 = px.histogram(df, x="Rating", template=template_style)
#     fig7.update_layout(height=500)
#     st.plotly_chart(fig7, use_container_width=True)
# 
# # ---------------- GRAPH 8: Salary by Job Role ----------------
# if "Job Title" in df.columns:
#     st.subheader("📦 Salary by Job Role")
#     fig8 = px.box(df, x="Job Title", y="Salary", template=template_style)
#     fig8.update_layout(height=500)
#     st.plotly_chart(fig8, use_container_width=True)
# 
# # ---------------- GRAPH 9: Avg Salary by Location ----------------
# if "Location" in df.columns:
#     st.subheader("📍 Avg Salary by Location")
#     loc_sal = df.groupby("Location")["Salary"].mean().reset_index()
#     fig9 = px.bar(loc_sal, x="Location", y="Salary", template=template_style)
#     fig9.update_layout(height=500)
#     st.plotly_chart(fig9, use_container_width=True)
# 
# # ---------------- GRAPH 10: Salary Trend ----------------
# st.subheader("📉 Salary Trend")
# df_sorted = df.sort_values("Salary")
# fig10 = px.line(df_sorted, y="Salary", template=template_style)
# fig10.update_traces(line=dict(width=2))
# fig10.update_layout(height=500)
# st.plotly_chart(fig10, use_container_width=True)

!pkill streamlit

from pyngrok import ngrok
import subprocess
import time

# kill old
ngrok.kill()
!pkill -f streamlit

# run streamlit
process = subprocess.Popen(
    ["streamlit", "run", "salary_dashbored.py", "--server.port", "8501"]
)

time.sleep(5)

# connect
public_url = ngrok.connect(addr=8501, proto="http")
print("LINK:", public_url)